/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ClassLoaderExperiments;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ClassNotFoundException, NoSuchMethodException, InvocationTargetException, InstantiationException, IllegalAccessException {
        System.out.println(new App().getGreeting());
        CustomClassLoader customClassLoader = new CustomClassLoader();
        Class<?> loadedClass = customClassLoader.loadClass("com.example.Add");
        Object instance = loadedClass.getDeclaredConstructor().newInstance();
        Method iAddMethod = loadedClass.getMethod("iAdd", int.class, int.class);

        // Call the iAdd method with sample inputs
        int result = (int) iAddMethod.invoke(instance, 5, 3);

        // Print the result
        System.out.println("Result of iAdd(5, 3): " + result);

    }
}
